name: Endpoint Test

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      endpoint:
        type: string
  workflow_call:
    inputs:
      endpoint:
        type: string

jobs:

  endpoint:
    name: ${{ inputs.endpoint }} (${{ matrix.env }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [local, cloud]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Install Dependencies
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/tools/install-deps.sh

      - name: Run System Tests
        env:
            TEST_ENVIRONMENT: ${{ matrix.env }}
        run: |
          if [[ "$TEST_ENVIRONMENT" == "cloud" ]]; then
            pytest -sv -n auto test/system-test/test_${{ inputs.endpoint }}.py
          else
            pytest -sv test/system-test/test_${{ inputs.endpoint }}.py
          fi
