name: Endpoint Test

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      endpoint:
        type: string
  workflow_call:
    inputs:
      endpoint:
        type: string

jobs:

  endpoint:
    name: ${{ inputs.endpoint }} (${{ matrix.env }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [ccf/sandbox_local]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log into Azure
        uses: azure/login@v2
        with:
          # Use a managed identity to authenticate to Azure
          # Use properties such as client-id, tenant-id, and subscription-id in the secrets and vars
          # The managed identity should have a federated credential with subject identiier repo:<organisation>/<repo>:pull_request
          # Use subject identiier repo:<organisation>/<repo>:ref:refs/heads/<branch> for running manual CI's
          client-id: ${{ secrets.MANAGED_ID_CLIENT_ID }}
          tenant-id: ${{ secrets.MANAGED_ID_TENANT_ID }}
          subscription-id: ${{ vars.SUBSCRIPTION }}

      - name: Install Dependencies
        env:
          GH_TOKEN: ${{ github.token }}
        run: ./scripts/tools/install-deps.sh

      - name: Run System Tests
        env:
            TEST_ENVIRONMENT: ${{ matrix.env }}
        run: pytest -sv test/system-test/test_${{ inputs.endpoint }}.py
